Be 05 add comments
knowde-academy/team-4-be pull request #1
Opened 2021-08-14 15:39 UTC by DanielOldak

2021-08-14 19:45 UTC, PatrykTyszka requested changes

2021-08-14 19:45 UTC, PatrykTyszka commented on app/controllers/api/v1/comments_controller.rb
> +          render json: { errors: form.errors.full_messages }, status: :unprocessable_entity
did you ask if frontend wants to get errors in this format?

2021-08-14 19:45 UTC, PatrykTyszka commented on app/forms/api/v1/comments_create_form.rb
> +      include ActiveModel::Model
1. First of all nice to see that someone knows what FormObject is and how to use it
2. Good job with namespace 

BUT 

it's overgrown with content... look at the create_recipe_comment. You could add this line inside the controller and move these validations to the model. It's even required to have these validations inside the model coz someone can create invalid data via rails console (you should prevent that as well). I would recommend removing this class ( even though I love it ) and move this logic to the controller coz at this moment it's to much :)

2021-08-14 19:45 UTC, PatrykTyszka commented on app/models/comment.rb
> +  # validations included in Api::V1::CommentCreateForm
remove this comment and add validations here. Do not forget to add knowde's comments e.g 
```
  class SomeModel
    # == Constants ============================================================

    # == Extensions ===========================================================

    # == Relationships ========================================================

    # == Validations ==========================================================

    # == Scopes ===============================================================

    # == Callbacks ============================================================

    # == Nested Attributes ====================================================

    # == Class Methods ========================================================

    # == Instance Methods =====================================================
  end
```

2021-08-14 19:45 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +  has_many :comments, serializer: Api::V1::CommentSerializer
not sure if you need these two lines if you have `def comment` please check

2021-08-14 19:45 UTC, PatrykTyszka commented on spec/controllers/api/v1/comments_controller_spec.rb
> +    let(:comment_params) { { author: comment.author, body: comment.body } }
Do not use a factory for creating params of comments. Do it explicitly using let's

2021-08-14 19:45 UTC, PatrykTyszka commented on spec/forms/api/v1/comments_create_form_spec.rb
> +describe Api::V1::CommentsCreateForm do
ehh :P you know what... wait for @h4b00 review :d maybe he will say that we should keep this Form Object :D

2021-08-14 19:45 UTC, PatrykTyszka commented on spec/serializers/api/v1/comment_serializer_spec.rb
> +  end
use factories for that -.-

2021-08-16 09:02 UTC, h4b00 requested changes

2021-08-16 11:59 UTC, PatrykTyszka approved these changes

2021-08-16 13:52 UTC, PatrykTyszka approved these changes

2021-08-16 19:50 UTC, h4b00 approved these changes
GJ

2021-08-17 06:47 UTC, merged