Be 10 limmit comments only to logged users
knowde-academy/team-4-be pull request #16
Opened 2021-08-20 11:04 UTC by DanielOldak

https://trello.com/c/Nzlnw6G3/38-be-10-limit-comments-only-to-logged-users-l
Only authenticated users are able to create comments

![Zrzut ekranu 2021-08-20 111005](https://user-images.githubusercontent.com/87693081/130223617-e5fe477a-edec-4571-bef3-e576aa1830f1.png)
![Zrzut ekranu 2021-08-20 125812](https://user-images.githubusercontent.com/87693081/130223620-e04377fa-a2af-44fb-af9b-1dfc7dacbc55.png)

To assign existing Comments to SystemUser we need to run tasks in lib/tasks at

2021-08-20 20:18 UTC, PatrykTyszka commented on app/models/system_user.rb
> +class SystemUser < User
n1

2021-08-20 20:18 UTC, PatrykTyszka commented on app/models/system_user.rb
> +    false
It's not required to return boolean here.

Instead of getting `first`, you can call exists?

2021-08-20 20:18 UTC, PatrykTyszka commented on app/models/user.rb
> +    type == 'SystemUser'
use const instead of string

2021-08-20 20:18 UTC, PatrykTyszka commented on app/serializers/api/v1/comment_serializer.rb
> +        object.author
```
Acceptance Criteria:
...
Comments without the user should return the author
Comments with the user should return the email of the author
```
I don't see anything about system users?

2021-08-20 20:18 UTC, PatrykTyszka commented on app/serializers/api/v1/comment_serializer.rb
> +        object.user
use delegate instead of that.

besides you forgot to add memo

2021-08-20 20:18 UTC, PatrykTyszka commented on db/migrate/20210819185409_add_type_to_users.rb
> +    add_column :users,:type, :string
```suggestion
    add_column :users, :type, :string
```

2021-08-20 20:18 UTC, PatrykTyszka commented on db/migrate/20210819210605_remove_author_validation_from_comments.rb
> +  end
👍

2021-08-20 20:18 UTC, PatrykTyszka commented on lib/tasks/set_system_user_for_all_existing_comments.rake
> +end
If you decided to split these two tasks, you should move the logic of SystemUser creation to a separate class. In this way, you can reuse this class in both tasks. Moreover, you don't need to break the task while SysyemUser does not exist. You could call the service here.

2021-08-20 20:29 UTC, DanielOldak commented on app/serializers/api/v1/comment_serializer.rb
> +        object.author
Seems like I've got diffrent acceptance criteria than what u see
![image](https://user-images.githubusercontent.com/87693081/130289963-5ef56161-dab7-4c4c-b9f6-efc42c08c4f8.png)

2021-08-23 09:54 UTC, h4b00 requested changes

2021-08-23 09:54 UTC, h4b00 commented on app/controllers/api/v1/comments_controller.rb
> +        params.require(:comment).permit(:author, :body).merge(user_id: current_api_v1_user.id)
use relation

2021-08-23 09:54 UTC, h4b00 commented on app/services/system_user_service.rb
> +  end
https://www.bigbinary.com/blog/rails-6-adds-create_or_find_by

2021-08-23 09:54 UTC, h4b00 commented on lib/tasks/set_system_user_for_all_existing_comments.rake
> +end
This should be in migration, no?

2021-08-31 10:52 UTC, PatrykTyszka commented on app/controllers/api/v1/recipes_controller.rb
> +          pagination:
Do you really need to lock these attributes inside the `pagination`?

2021-08-31 10:52 UTC, PatrykTyszka commented on app/models/system_user.rb
> +  end
👍

2021-08-31 10:52 UTC, PatrykTyszka commented on app/models/system_user.rb
> +    self.errors.add(:base, 'SystemUser already exists')
self is not necessary ( we're using self only for setters )

2021-08-31 10:52 UTC, PatrykTyszka commented on app/serializers/api/v1/comment_serializer.rb
> +      end
👍

2021-08-31 10:52 UTC, PatrykTyszka commented on app/models/ingredient.rb
> +class Ingredient < ApplicationRecord
it should not be here.

2021-08-31 10:52 UTC, PatrykTyszka commented on app/services/system_user_service.rb
> +end
it's useless, please move this logit to the SystemUser class.

2021-08-31 10:52 UTC, PatrykTyszka commented on db/migrate/20210822130020_create_ingredients.rb
> +    end
?

2021-08-31 10:53 UTC, PatrykTyszka commented on lib/tasks/set_system_user_for_all_existing_comments.rake
> +end
Inside migration or in the rake task. Besides, it should be one in the ONE single QUERY.

2021-08-31 12:45 UTC, closed without merging