Be 07 crud products
knowde-academy/team-4-be pull request #2
Opened 2021-08-15 15:33 UTC by plokijro

Adding CRUD product

2021-08-16 07:58 UTC, PatrykTyszka requested changes

2021-08-16 07:58 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +    render json: { data: ActiveModelSerializers::SerializableResource.new(Product.all, each_serializer: ProductSerializer)}
did you ask FE that we want to send products in `data` key? Why not `products`?

2021-08-16 07:58 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +    render json: ProductSerializer.new(@product).to_h
If you create serializer with the same namespace you don't need to use it explicitly here. It should work automatically

2021-08-16 07:58 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +      render json: { errors: product.errors }, status: :unprocessable_entity
Did you check how it looks like in the response?

2021-08-16 07:58 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +      render json: { errors: product.errors }, status: :unprocessable_entity
IMO you should send product.errors.full_messages or .messages

2021-08-16 07:58 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +  private
```suggestion
  end
  
  private
```

2021-08-16 07:58 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +  before_action :set_product, except: [:index, :create]
only is better than expect coz it's more readable ( it's only my opinion )

2021-08-16 07:58 UTC, PatrykTyszka commented on config/routes.rb
> +      resources :products
add `only` coz you don't want to create 'new' and 'edit' paths.

2021-08-16 07:58 UTC, PatrykTyszka commented on db/migrate/20210815071443_create_products.rb
> +      t.string :name
add index uniq for this field to be sure that no one adds a product with the same name. Protection in the model is not enough.

2021-08-16 07:58 UTC, PatrykTyszka commented on spec/controllers/api/v1/products_controller_spec.rb
> +    let(:expected_response) { ProductSerializer.new(product).to_json}
No.
you should show explicitly what you are going to test. 
```
let(:expected) do
  {
    name: 'some name',
    ..
end

...

expect(JSON.parse(response.body).to eq(expected)
```

2021-08-16 07:58 UTC, PatrykTyszka commented on spec/controllers/api/v1/products_controller_spec.rb
> +        end.to raise_exception(ActiveRecord::RecordNotFound)
it's a common behavior so you don't need to test if rails works correct :D

2021-08-16 07:58 UTC, PatrykTyszka commented on spec/controllers/api/v1/products_controller_spec.rb
> +        expect { delete :destroy, params: { id: product.id } }.to change(Product, :count).by(-1)
I see duplication here so you can create let(:call) { delete :destroy, params: { id: product.id } } and use it in these tests.

2021-08-16 07:58 UTC, PatrykTyszka commented on spec/factories/products.rb
> +    name { Faker::Food.ingredient }
as I remember that we have a problem with faker coz sometimes it returns the same name for two different products. It's why we're using the sequence in that cases.

2021-08-16 07:58 UTC, PatrykTyszka commented on spec/models/product_spec.rb
> +    it { is_expected.not_to allow_value("").for(:name)}
```suggestion
    it { is_expected.to validate_uniqueness_of(:name) }
    it { is_expected.not_to allow_value('').for(:name) }
```

2021-08-16 07:58 UTC, PatrykTyszka commented on spec/requests/api/v1/products_spec.rb
> +  end
?

2021-08-16 07:58 UTC, PatrykTyszka commented on spec/serializers/product_serializer_spec.rb
> +end
```suggestion
end

```

2021-08-16 09:39 UTC, plokijro commented on app/controllers/api/v1/products_controller.rb
> +  before_action :set_product, except: [:index, :create]
In this situation wouldn't "expect" better, because of less elements in array?

2021-08-16 09:46 UTC, plokijro commented on app/controllers/api/v1/products_controller.rb
> +    render json: { data: ActiveModelSerializers::SerializableResource.new(Product.all, each_serializer: ProductSerializer)}
I spoke with team and we decided that the option propsed by you is better.

2021-08-16 09:48 UTC, plokijro commented on app/controllers/api/v1/products_controller.rb
> +      render json: { errors: product.errors }, status: :unprocessable_entity
Yeah, you are rigtht. We decided to send errors.messages.

2021-08-16 10:30 UTC, plokijro commented on app/controllers/api/v1/products_controller.rb
> +  before_action :set_product, except: [:index, :create]
Discussed on Slack.

2021-08-16 11:13 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +        render json: { products: ActiveModelSerializers::SerializableResource
try to break it in better way :P

2021-08-16 11:13 UTC, PatrykTyszka commented on config/routes.rb
> +      resources :products
?

2021-08-16 11:13 UTC, PatrykTyszka commented on db/migrate/20210815071443_create_products.rb
> +      t.string :name
?

2021-08-16 13:07 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +              .new(Product.all, each_serializer: ProductSerializer) }
```suggestion
  render json: { 
    products: ActiveModelSerializers::SerializableResource.new(
      Product.all,
      each_serializer: ProductSerializer
    )
  }
```

2021-08-16 13:07 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +        end
never happened

2021-08-16 13:07 UTC, PatrykTyszka commented on spec/controllers/api/v1/products_controller_spec.rb
> +
```suggestion
describe '[POST] #create' do
  let(:name) { 'Cucumber' }
  let(:post_request) do
    post :create, params: { product: { name: name } }
  end

  context 'with valid params' do
    it 'create product' do
      expect { post_request }.to change(Product, :count).by(1)
    end
  end

  context 'with invalid params' do
    let(:name) { '' }

    it "doesn't create product" do
      expect { post_request }.not_to change(Product, :count)
    end
  end
end
```

2021-08-16 13:07 UTC, PatrykTyszka commented on spec/factories/products.rb
> +    end
```suggestion
      sequence(:name) { |number| "#{number} #{Faker::Food.ingredient}" }
```

2021-08-16 13:07 UTC, PatrykTyszka commented on true
> +      create    db/migrate/20210816114107_add_index_to_products.rb
remove?

2021-08-16 19:51 UTC, PatrykTyszka approved these changes

2021-08-16 19:51 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +        }
👍

2021-08-16 19:51 UTC, PatrykTyszka commented on app/controllers/api/v1/products_controller.rb
> +        @product.destroy
add ! so if something went wrong we will display an error instead of sending 200 :P

2021-08-16 20:25 UTC, plokijro commented on app/controllers/api/v1/products_controller.rb
> +        @product.destroy
Done :)

2021-08-17 12:48 UTC, h4b00 approved these changes
LGTM. 👏

2021-08-17 13:05 UTC, merged