Be 12 limit creating recipes only to logged users
knowde-academy/team-4-be pull request #20
Opened 2021-08-21 19:11 UTC by DanielOldak

Only authenticated users are able to manage recipes

![Zrzut ekranu 2021-08-21 195045](https://user-images.githubusercontent.com/87693081/130332475-a5f1502b-b39c-432b-b7f8-8ddcbf84521a.png)
![Zrzut ekranu 2021-08-21 195124](https://user-images.githubusercontent.com/87693081/130332476-5c5a308e-5dd7-478f-bcd8-f7e366e176d9.png)
![Zrzut ekranu 2021-08-21 195200](https://user-images.githubusercontent.com/87693081/130332477-296dcb56-21e2-4742-b480-acbe5882e0b3.png)

In order to set SystemUser for existing comments run set_system_user_for_all_existing_recipes rake task

2021-08-21 19:18 UTC, DanielOldak commented
I've set a bad branch name originally, thats why there is wrong naming in commits.

2021-08-23 10:20 UTC, PatrykTyszka requested changes

2021-08-23 10:20 UTC, PatrykTyszka commented on app/serializers/api/v1/comment_serializer.rb
> +      end
use delegate

2021-08-23 10:20 UTC, PatrykTyszka commented on lib/tasks/set_system_user_for_all_existing_comments.rake
> +  end
Maybe you can make one query instead of N?

2021-08-23 10:20 UTC, PatrykTyszka commented on lib/tasks/set_system_user_for_all_existing_recipes.rake
> +    recipe.save
same here.. one query should be enough.

2021-08-23 10:20 UTC, PatrykTyszka commented on app/services/system_user_service.rb
> +    puts 'SystemUser successfuly created'
? puts - remove.

2021-08-23 10:20 UTC, PatrykTyszka commented on app/services/system_user_service.rb
> +class SystemUserService
I think you can move this logic to the User model.

```
User.system_user

def self.system_user
  # ...
end
```

2021-09-01 08:39 UTC, closed without merging