Be 03 add level
knowde-academy/team-4-be pull request #4
Opened 2021-08-17 11:32 UTC by Miwysocki

[BE-03] Added `level` field to recipes

2021-08-17 11:39 UTC, h4b00 requested changes

2021-08-17 11:39 UTC, h4b00 commented on app/models/recipe.rb
> +
?

2021-08-17 11:39 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +    end
```
return "unknown" unless object.level

object.level
```

2021-08-17 11:39 UTC, h4b00 commented on app/serializers/recipe_serializer.rb
> +  attributes :id, :name, :content ,:level
fix `,` here

2021-08-17 11:39 UTC, h4b00 commented on spec/factories/recipes.rb
> +    level {Faker::Number.within(range: 1..5)}
put ` ` inside `{`

2021-08-17 11:39 UTC, h4b00 commented on app/models/recipe.rb
> +  validates :level, numericality:{ greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
the level is required or not?

2021-08-17 11:43 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +    end
and also add const instead of string

2021-08-17 11:43 UTC, PatrykTyszka commented on app/models/recipe.rb
> +  validates :level, numericality:{ greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
nop, so we need to add one more option ;)

2021-08-18 08:05 UTC, PatrykTyszka requested changes

2021-08-18 08:05 UTC, PatrykTyszka commented on app/models/recipe.rb
> +end
Please fix it... you should have empty line at the end of file ( ALWAYS )

2021-08-18 08:05 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +  MESSAGE_IF_EMPTY = 'unknown'
const before attrubutes and add freeze

2021-08-18 08:05 UTC, PatrykTyszka commented on app/serializers/recipe_serializer.rb
> +
remove empty line

2021-08-18 08:05 UTC, PatrykTyszka commented
Fix conflicts

2021-08-18 15:35 UTC, PatrykTyszka approved these changes

2021-08-20 11:06 UTC, merged